{
 "title": "MIV pro Rekorder",
 "time": { "from": "2019-06-30T21:59:59.000Z", "to": "2020-06-14T21:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "externalId",
    "label": "DetektorPrimary",
    "query": "SELECT EXTERNALID FROM TRAFFICRECORDER"
   }
  ]
 },
 "panels": [
  {
   "title": "MIV pro Detektor Vergleich",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(RECORDDATE, \"1d\"),\n  CARCOUNT AS \"MIV\",\n  EXTERNALID\nFROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\nWHERE EXTERNALID in ($externalId) and $__timeFilter(RECORDDATE)\nORDER BY time ASC, EXTERNALID ASC"
    }
   ]
  },
  {
   "title": "MIV pro Detektor Vergleich",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(RECORDDATE, \"1d\"),\n  CARCOUNT AS \"MIV\",\n  EXTERNALID\nFROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\nWHERE EXTERNALID in ($externalId) and $__timeFilter(RECORDDATE)\nORDER BY time ASC, EXTERNALID ASC"
    }
   ]
  },
  {
   "title": "Durschnittliche MIV am Wochenende und unter der Woche pro Detektor",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  Weekend.EXTERNALID as \"Detektor\",\n  NoWeekend.AvgInWeek as \"Durchschnitt unter der Woche\",\n  Weekend.AvgInWeek as \"Durchschnitt am Wochenende\"\nFROM \n (SELECT\n     AVG(CARCOUNT) as \"AvgInWeek\", EXTERNALID\n     FROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\n     WHERE \n      EXTERNALID in ($externalId) and \n      WEEKDAY(RECORDDATE) in (5, 6) = 0 and \n      $__timeFilter(RECORDDATE)\n     GROUP BY EXTERNALID\n     ORDER BY EXTERNALID ASC\n ) NoWeekend INNER JOIN\n(SELECT\n    AVG(CARCOUNT) as \"AvgInWeek\", EXTERNALID\n  FROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\n  WHERE \n    EXTERNALID in ($externalId) and \n    WEEKDAY(RECORDDATE) in (5, 6) = 1 and \n    $__timeFilter(RECORDDATE)\n  GROUP BY EXTERNALID\n  ORDER BY EXTERNALID ASC\n) Weekend on (Weekend.EXTERNALID = NoWeekend.EXTERNALID)\n\nWHERE Weekend.EXTERNALID in ($externalId)\nGROUP BY Weekend.EXTERNALID\nORDER BY Weekend.EXTERNALID ASC"
    }
   ]
  },
  {
   "title": "Durchschnittliche MIV pro Detektor im Zeitraum",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(CARCOUNT) AS \"Durchschnitt MIV\",\n  EXTERNALID\nFROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\nWHERE EXTERNALID in ($externalId) and $__timeFilter(RECORDDATE)\nGROUP BY EXTERNALID\nORDER BY EXTERNALID ASC"
    }
   ]
  },
  {
   "title": "Straßenauslastung im Zeitraum",
   "type": "heatmap-new",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(RECORDDATE, \"24h\"),\n  CARCOUNT AS \"MIV\",\n  EXTERNALID\nFROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\nWHERE EXTERNALID in ($externalId) and $__timeFilter(RECORDDATE)\nORDER BY time ASC, EXTERNALID ASC"
    }
   ]
  },
  {
   "title": "Relative Straßenauslastung im Zeitraum",
   "type": "heatmap-new",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(RECORDDATE, \"24h\"),\n  CARCOUNT / MAXCOUNT AS \"MIV\",\n  EXTERNALID\nFROM TRAFFICRECORD INNER JOIN (\n  TRAFFICRECORDER\n    INNER JOIN (\n      SELECT MAX(CARCOUNT) as MAXCOUNT, TRAFFICRECORDER.ID \n      FROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\n      GROUP BY ID\n    ) minMax on minMax.ID = TRAFFICRECORDER.ID) on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\nWHERE EXTERNALID in ($externalId) and $__timeFilter(RECORDDATE)\nORDER BY time ASC, EXTERNALID ASC"
    }
   ]
  },
  {
   "title": "Durschnittliche MIV pro Wochentag pro Detektor",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(CARCOUNT) AS \"Durchschnitt MIV\",\n  (WEEKDAY(RECORDDATE) * 1000 * 60 * 60 * 24 + 4 * 1000 * 24 * 60 * 60 ) AS \"time\", -- abusing date format so that monday (0) is actually a monday\n  EXTERNALID\nFROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\nWHERE EXTERNALID in ($externalId) and $__timeFilter(RECORDDATE)\nGROUP BY time, EXTERNALID\nORDER BY time ASC, EXTERNALID ASC"
    }
   ]
  },
  {
   "title": "Ein-/Ausfahrten MIV während und außerhalb WU (Detektor gefiltert)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  NoWeekend.CITYDIRECTION as \"Richtung\",\n  NoWeekend.NotWU as \"Durchschnitt außerhalb WU\",\n  Weekend.WU as \"Durchschnitt im WU\"\nFROM \n (SELECT\n     AVG(CARCOUNT) as \"NotWU\", EXTERNALID, CITYDIRECTION\n     FROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\n     WHERE \n      EXTERNALID in ($externalId) and \n      PLANTHOLIDAY = 0\n     GROUP BY EXTERNALID\n     ORDER BY EXTERNALID ASC\n ) NoWeekend INNER JOIN\n(SELECT\n    AVG(CARCOUNT) as \"WU\", EXTERNALID\n  FROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\n  WHERE \n    EXTERNALID in ($externalId) and \n    PLANTHOLIDAY = 1\n  GROUP BY EXTERNALID\n  ORDER BY EXTERNALID ASC\n) Weekend on (Weekend.EXTERNALID = NoWeekend.EXTERNALID)\n\nWHERE Weekend.EXTERNALID in ($externalId)\nGROUP BY NoWeekend.CITYDIRECTION\nORDER BY NoWeekend.CITYDIRECTION ASC"
    }
   ]
  },
  {
   "title": "Durchschnittliche MIV (Gesamtvergleich WU/kein WU)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT\n  Weekend.EXTERNALID as \"Detektor\",\n  NoWeekend.NotHoliday as \"Durchschnitt außerhalb WU\",\n  Weekend.Holiday as \"Durchschnitt im WU\"\nFROM \n (SELECT\n     AVG(CARCOUNT) as \"NotHoliday\", EXTERNALID\n     FROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\n     WHERE \n      EXTERNALID in ($externalId) and \n      PLANTHOLIDAY = 0\n     GROUP BY EXTERNALID\n     ORDER BY EXTERNALID ASC\n ) NoWeekend INNER JOIN\n(SELECT\n    AVG(CARCOUNT) as \"Holiday\", EXTERNALID\n  FROM TRAFFICRECORD INNER JOIN TRAFFICRECORDER on (TRAFFICRECORD.TRAFFICRECORDER_ID = TRAFFICRECORDER.ID)\n  WHERE \n    EXTERNALID in ($externalId) and \n    PLANTHOLIDAY = 1\n  GROUP BY EXTERNALID\n  ORDER BY EXTERNALID ASC\n) Weekend on (Weekend.EXTERNALID = NoWeekend.EXTERNALID)\n\nWHERE Weekend.EXTERNALID in ($externalId)\nGROUP BY Weekend.EXTERNALID\nORDER BY Weekend.EXTERNALID ASC"
    }
   ]
  }
 ]
}